language: node_js
node_js: node
stages:
  - Unit tests
  - Build and deploy
matrix:
  include:
    - os: linux
      stage: Unit tests
      addons:
        chrome: stable
      env:
        - BROWSER=ChromeHeadless
    - os: linux
      stage: Unit tests
      addons:
        firefox: latest
      env:
        - BROWSER=Firefox MOZ_HEADLESS=1
    - os: osx
      stage: Unit tests
      addons:
        chrome: stable
      env:
        - BROWSER=ChromeHeadless
    - os: osx
      stage: Unit tests
      addons:
        firefox: latest
      env:
        - BROWSER=Firefox MOZ_HEADLESS=1
    - os: windows
      stage: Unit tests
      before_install:
        - choco install googlechrome
      env:
        - BROWSER=Chrome
    - os: windows
      stage: Unit tests
      before_install:
        - choco install firefox
      env:
        - BROWSER=Firefox MOZ_HEADLESS=1
    - os: windows
      stage: Unit tests
      env:
        - BROWSER=Edge
    - stage: Build and deploy
      script: yarn build
      env:
        - BROWSER=chrome
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn yarn deploy:${BROWSER}
        on:
          branch: master
          tags: true
    - stage: Build and deploy
      script: yarn build
      env:
        - BROWSER=firefox
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn deploy:${BROWSER}
        on:
          branch: master
          tags: true
  allow_failures:
    - os: windows
      stage: Unit tests
